default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# Our movies.db file is our primary database:
movies: &movies
  <<: *default
  database: db/movies.db

development:
  <<: *movies

test:
  <<: *movies

production:
  <<: *movies

# The separate database for ratings is configured here:
ratings: &ratings
  <<: *default
  database: db/ratings.db

ratings_development:
  <<: *ratings

ratings_test:
  <<: *ratings

ratings_production:
  <<: *ratings
